package com.shinto.studentregistration

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "notesTable")
class Note(
    @ColumnInfo(name = "Name") var noteTitle: String,
    @ColumnInfo(name = "Class") var noteDescription: String,
    @ColumnInfo(name = "Dob") var noteDob: String,
    @ColumnInfo(name = "School") var noteSchool: String

) {
    // This code the id is autogenerated
    @PrimaryKey(autoGenerate = true)
    var id = 0
}

