package com.shinto.studentregistration

import android.graphics.Bitmap
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

// 1
// This is model class
@Entity(tableName = "notesTable")
class Note(
    @ColumnInfo(name = "Name") var noteTitle: String,
    @ColumnInfo(name = "Class") var noteDescription: String,
    @ColumnInfo(name="Dob") var noteDob:String,
    @ColumnInfo(name="School")var noteSchool:String

    //  @ColumnInfo(typeAffinity = ColumnInfo.BLOB)
    // byte[] image;
    // @ColumnInfo(name = "Timestamp") val timeStamp: String
) {
    // This code the id is autogenerated
    @PrimaryKey(autoGenerate = true)
    var id = 0

//    ColumnInfo(typeAffinity = ColumnInfo.BLOB)
//    var data: ByteArray? = null
}

